/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.jooq.tables.daos;


import com.diamondfsd.jooq.learn.extend.ExtendDAOImpl;
import com.diamondfsd.jooq.learn.jooq.tables.TS1User;
import com.diamondfsd.jooq.learn.jooq.tables.records.S1UserRecord;
import com.diamondfsd.jooq.learn.entity.S1User;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class S1UserDao extends ExtendDAOImpl<S1UserRecord, S1User, Integer> {

    /**
     * Create a new S1UserDao without any configuration
     */
    public S1UserDao() {
        super(TS1User.S1_USER, S1User.class);
    }

    /**
     * Create a new S1UserDao with an attached configuration
     */
    @Autowired
    public S1UserDao(Configuration configuration) {
        super(TS1User.S1_USER, S1User.class, configuration);
    }

    @Override
    public Integer getId(S1User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TS1User.S1_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<S1User> fetchById(Integer... values) {
        return fetch(TS1User.S1_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public S1User fetchOneById(Integer value) {
        return fetchOne(TS1User.S1_USER.ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<S1User> fetchByUsername(String... values) {
        return fetch(TS1User.S1_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<S1User> fetchByEmail(String... values) {
        return fetch(TS1User.S1_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>address BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<S1User> fetchByAddress(String... values) {
        return fetch(TS1User.S1_USER.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfCreateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS1User.S1_USER.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<S1User> fetchByCreateTime(Timestamp... values) {
        return fetch(TS1User.S1_USER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1User> fetchRangeOfUpdateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS1User.S1_USER.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<S1User> fetchByUpdateTime(Timestamp... values) {
        return fetch(TS1User.S1_USER.UPDATE_TIME, values);
    }
}
