/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 表字段超22
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IS4ColumenGt22 extends Serializable {

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.id</code>. id
     */
    public void setId(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.id</code>. id
     */
    public Integer getId();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_1</code>. 列1
     */
    public void setColumn_1(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_1</code>. 列1
     */
    public Integer getColumn_1();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_2</code>. 列2
     */
    public void setColumn_2(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_2</code>. 列2
     */
    public Integer getColumn_2();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_3</code>. 列3
     */
    public void setColumn_3(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_3</code>. 列3
     */
    public Integer getColumn_3();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_4</code>. 列4
     */
    public void setColumn_4(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_4</code>. 列4
     */
    public Integer getColumn_4();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_5</code>. 列5
     */
    public void setColumn_5(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_5</code>. 列5
     */
    public Integer getColumn_5();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_6</code>. 列6
     */
    public void setColumn_6(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_6</code>. 列6
     */
    public Integer getColumn_6();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_7</code>. 列7
     */
    public void setColumn_7(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_7</code>. 列7
     */
    public Integer getColumn_7();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_8</code>. 列8
     */
    public void setColumn_8(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_8</code>. 列8
     */
    public Integer getColumn_8();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_9</code>. 列_9
     */
    public void setColumn_9(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_9</code>. 列_9
     */
    public Integer getColumn_9();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_10</code>. 列10
     */
    public void setColumn_10(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_10</code>. 列10
     */
    public Integer getColumn_10();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_11</code>. 列11
     */
    public void setColumn_11(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_11</code>. 列11
     */
    public Integer getColumn_11();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_12</code>. 列12
     */
    public void setColumn_12(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_12</code>. 列12
     */
    public Integer getColumn_12();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_13</code>. 列13
     */
    public void setColumn_13(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_13</code>. 列13
     */
    public Integer getColumn_13();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_14</code>. 列14
     */
    public void setColumn_14(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_14</code>. 列14
     */
    public Integer getColumn_14();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_15</code>. 列15
     */
    public void setColumn_15(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_15</code>. 列15
     */
    public Integer getColumn_15();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_16</code>. 列16
     */
    public void setColumn_16(String value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_16</code>. 列16
     */
    public String getColumn_16();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_17</code>. 列17
     */
    public void setColumn_17(String value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_17</code>. 列17
     */
    public String getColumn_17();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_18</code>. 列18
     */
    public void setColumn_18(String value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_18</code>. 列18
     */
    public String getColumn_18();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_19</code>. 列19
     */
    public void setColumn_19(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_19</code>. 列19
     */
    public Timestamp getColumn_19();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_20</code>. 列20
     */
    public void setColumn_20(Boolean value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_20</code>. 列20
     */
    public Boolean getColumn_20();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_21</code>. 列21
     */
    public void setColumn_21(Byte value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_21</code>. 列21
     */
    public Byte getColumn_21();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_22</code>. 列22
     */
    public void setColumn_22(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_22</code>. 列22
     */
    public Integer getColumn_22();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_23</code>. 列23
     */
    public void setColumn_23(Integer value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_23</code>. 列23
     */
    public Integer getColumn_23();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime();

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IS4ColumenGt22
     */
    public void from(com.diamondfsd.jooq.learn.codegen.tables.interfaces.IS4ColumenGt22 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IS4ColumenGt22
     */
    public <E extends com.diamondfsd.jooq.learn.codegen.tables.interfaces.IS4ColumenGt22> E into(E into);
}
