/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IS1User extends Serializable {

    /**
     * Setter for <code>learn-jooq.s1_user.id</code>. ID
     */
    public void setId(Integer value);

    /**
     * Getter for <code>learn-jooq.s1_user.id</code>. ID
     */
    public Integer getId();

    /**
     * Setter for <code>learn-jooq.s1_user.username</code>.
     */
    public void setUsername(String value);

    /**
     * Getter for <code>learn-jooq.s1_user.username</code>.
     */
    public String getUsername();

    /**
     * Setter for <code>learn-jooq.s1_user.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>learn-jooq.s1_user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>learn-jooq.s1_user.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>learn-jooq.s1_user.address</code>.
     */
    public String getAddress();

    /**
     * Setter for <code>learn-jooq.s1_user.create_time</code>.
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s1_user.create_time</code>.
     */
    public Timestamp getCreateTime();

    /**
     * Setter for <code>learn-jooq.s1_user.update_time</code>.
     */
    public void setUpdateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s1_user.update_time</code>.
     */
    public Timestamp getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IS1User
     */
    public void from(com.diamondfsd.jooq.learn.codegen.learn_jooq.tables.interfaces.IS1User from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IS1User
     */
    public <E extends com.diamondfsd.jooq.learn.codegen.learn_jooq.tables.interfaces.IS1User> E into(E into);
}
