/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.s1.codegen;


import com.diamondfsd.jooq.learn.s1.codegen.tables.S1User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn-jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>learn-jooq.s1-user</code>.
     */
    public static final S1User S1_USER = S1User.S1_USER;
}
