/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen;


import com.diamondfsd.jooq.learn.codegen.tables.TS1User;
import com.diamondfsd.jooq.learn.codegen.tables.TS2UserMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LearnJooq extends SchemaImpl {

    private static final long serialVersionUID = 1223962513;

    /**
     * The reference instance of <code>learn-jooq</code>
     */
    public static final LearnJooq LEARN_JOOQ = new LearnJooq();

    /**
     * USER TABLE
     */
    public final TS1User S1_USER = com.diamondfsd.jooq.learn.codegen.tables.TS1User.S1_USER;

    /**
     * 用户消息内容
     */
    public final TS2UserMessage S2_USER_MESSAGE = com.diamondfsd.jooq.learn.codegen.tables.TS2UserMessage.S2_USER_MESSAGE;

    /**
     * No further instances allowed
     */
    private LearnJooq() {
        super("learn-jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TS1User.S1_USER,
            TS2UserMessage.S2_USER_MESSAGE);
    }
}
