/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen;


import com.diamondfsd.jooq.learn.codegen.tables.TS1User;
import com.diamondfsd.jooq.learn.codegen.tables.TS2UserMessage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn-jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * USER TABLE
     */
    public static final TS1User S1_USER = TS1User.S1_USER;

    /**
     * 用户消息内容
     */
    public static final TS2UserMessage S2_USER_MESSAGE = TS2UserMessage.S2_USER_MESSAGE;
}
