/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.TS7User;
import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.records.S7UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>learn-jooq-2</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<S7UserRecord, Integer> IDENTITY_S7_USER = Identities0.IDENTITY_S7_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<S7UserRecord> KEY_S7_USER_PRIMARY = UniqueKeys0.KEY_S7_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<S7UserRecord, Integer> IDENTITY_S7_USER = Internal.createIdentity(TS7User.S7_USER, TS7User.S7_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<S7UserRecord> KEY_S7_USER_PRIMARY = Internal.createUniqueKey(TS7User.S7_USER, "KEY_s7_user_PRIMARY", TS7User.S7_USER.ID);
    }
}
