/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.TS7User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LearnJooq_2 extends SchemaImpl {

    private static final long serialVersionUID = -1776879995;

    /**
     * The reference instance of <code>learn-jooq-2</code>
     */
    public static final LearnJooq_2 LEARN_JOOQ_2 = new LearnJooq_2();

    /**
     * USER TABLE
     */
    public final TS7User S7_USER = com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.TS7User.S7_USER;

    /**
     * No further instances allowed
     */
    private LearnJooq_2() {
        super("learn-jooq-2", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TS7User.S7_USER);
    }
}
