/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.TS7User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn-jooq-2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * USER TABLE
     */
    public static final TS7User S7_USER = TS7User.S7_USER;
}
