/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq.tables.pojos;


import com.diamondfsd.jooq.learn.codegen.learn_jooq.tables.interfaces.IS4UnionKey;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4UnionKeyPojo implements IS4UnionKey {

    private static final long serialVersionUID = -1201986280;

    private Integer   uk_1;
    private Integer   uk_2;
    private Timestamp createTime;
    private Timestamp updateTime;

    public S4UnionKeyPojo() {}

    public S4UnionKeyPojo(IS4UnionKey value) {
        this.uk_1 = value.getUk_1();
        this.uk_2 = value.getUk_2();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public S4UnionKeyPojo(
        Integer   uk_1,
        Integer   uk_2,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.uk_1 = uk_1;
        this.uk_2 = uk_2;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Override
    public Integer getUk_1() {
        return this.uk_1;
    }

    @Override
    public void setUk_1(Integer uk_1) {
        this.uk_1 = uk_1;
    }

    @Override
    public Integer getUk_2() {
        return this.uk_2;
    }

    @Override
    public void setUk_2(Integer uk_2) {
        this.uk_2 = uk_2;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S4UnionKeyPojo (");

        sb.append(uk_1);
        sb.append(", ").append(uk_2);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS4UnionKey from) {
        setUk_1(from.getUk_1());
        setUk_2(from.getUk_2());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS4UnionKey> E into(E into) {
        into.from(this);
        return into;
    }
}
