/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.jooq.tables.pojos;


import com.diamondfsd.jooq.learn.jooq.tables.interfaces.IS2UserMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户消息内容
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S2UserMessagePojo implements IS2UserMessage {

    private static final long serialVersionUID = 1238187964;

    private Integer   id;
    private Integer   userId;
    private String    messageTitle;
    private String    messageContent;
    private Timestamp createTime;
    private Timestamp updateTime;

    public S2UserMessagePojo() {}

    public S2UserMessagePojo(IS2UserMessage value) {
        this.id = value.getId();
        this.userId = value.getUserId();
        this.messageTitle = value.getMessageTitle();
        this.messageContent = value.getMessageContent();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public S2UserMessagePojo(
        Integer   id,
        Integer   userId,
        String    messageTitle,
        String    messageContent,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.userId = userId;
        this.messageTitle = messageTitle;
        this.messageContent = messageContent;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String getMessageTitle() {
        return this.messageTitle;
    }

    @Override
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

    @Override
    public String getMessageContent() {
        return this.messageContent;
    }

    @Override
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S2UserMessagePojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(messageTitle);
        sb.append(", ").append(messageContent);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS2UserMessage from) {
        setId(from.getId());
        setUserId(from.getUserId());
        setMessageTitle(from.getMessageTitle());
        setMessageContent(from.getMessageContent());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS2UserMessage> E into(E into) {
        into.from(this);
        return into;
    }
}
