/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.records;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.TS7User;
import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.interfaces.IS7User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S7UserRecord extends UpdatableRecordImpl<S7UserRecord> implements Record6<Integer, String, String, String, Timestamp, Timestamp>, IS7User {

    private static final long serialVersionUID = -1631682776;

    /**
     * Setter for <code>learn-jooq-2.s7_user.id</code>. ID
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.id</code>. ID
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>learn-jooq-2.s7_user.username</code>.
     */
    @Override
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.username</code>.
     */
    @Override
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>learn-jooq-2.s7_user.email</code>.
     */
    @Override
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>learn-jooq-2.s7_user.address</code>.
     */
    @Override
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.address</code>.
     */
    @Override
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>learn-jooq-2.s7_user.create_time</code>.
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.create_time</code>.
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>learn-jooq-2.s7_user.update_time</code>.
     */
    @Override
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>learn-jooq-2.s7_user.update_time</code>.
     */
    @Override
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TS7User.S7_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return TS7User.S7_USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return TS7User.S7_USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return TS7User.S7_USER.ADDRESS;
    }

    @Override
    public Field<Timestamp> field5() {
        return TS7User.S7_USER.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field6() {
        return TS7User.S7_USER.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getAddress();
    }

    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getAddress();
    }

    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    @Override
    public S7UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public S7UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public S7UserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public S7UserRecord value4(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public S7UserRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public S7UserRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public S7UserRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS7User from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setEmail(from.getEmail());
        setAddress(from.getAddress());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS7User> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S7UserRecord
     */
    public S7UserRecord() {
        super(TS7User.S7_USER);
    }

    /**
     * Create a detached, initialised S7UserRecord
     */
    public S7UserRecord(Integer id, String username, String email, String address, Timestamp createTime, Timestamp updateTime) {
        super(TS7User.S7_USER);

        set(0, id);
        set(1, username);
        set(2, email);
        set(3, address);
        set(4, createTime);
        set(5, updateTime);
    }
}
