/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.Indexes;
import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.Keys;
import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.LearnJooq_2;
import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.records.S7UserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TS7User extends TableImpl<S7UserRecord> {

    private static final long serialVersionUID = 2109991215;

    /**
     * The reference instance of <code>learn-jooq-2.s7_user</code>
     */
    public static final TS7User S7_USER = new TS7User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<S7UserRecord> getRecordType() {
        return S7UserRecord.class;
    }

    /**
     * The column <code>learn-jooq-2.s7_user.id</code>. ID
     */
    public final TableField<S7UserRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "ID");

    /**
     * The column <code>learn-jooq-2.s7_user.username</code>.
     */
    public final TableField<S7UserRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>learn-jooq-2.s7_user.email</code>.
     */
    public final TableField<S7UserRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>learn-jooq-2.s7_user.address</code>.
     */
    public final TableField<S7UserRecord, String> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>learn-jooq-2.s7_user.create_time</code>.
     */
    public final TableField<S7UserRecord, Timestamp> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>learn-jooq-2.s7_user.update_time</code>.
     */
    public final TableField<S7UserRecord, Timestamp> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>learn-jooq-2.s7_user</code> table reference
     */
    public TS7User() {
        this(DSL.name("s7_user"), null);
    }

    /**
     * Create an aliased <code>learn-jooq-2.s7_user</code> table reference
     */
    public TS7User(String alias) {
        this(DSL.name(alias), S7_USER);
    }

    /**
     * Create an aliased <code>learn-jooq-2.s7_user</code> table reference
     */
    public TS7User(Name alias) {
        this(alias, S7_USER);
    }

    private TS7User(Name alias, Table<S7UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TS7User(Name alias, Table<S7UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("USER TABLE"));
    }

    public <O extends Record> TS7User(Table<O> child, ForeignKey<O, S7UserRecord> key) {
        super(child, key, S7_USER);
    }

    @Override
    public Schema getSchema() {
        return LearnJooq_2.LEARN_JOOQ_2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S7_USER_PRIMARY);
    }

    @Override
    public Identity<S7UserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S7_USER;
    }

    @Override
    public UniqueKey<S7UserRecord> getPrimaryKey() {
        return Keys.KEY_S7_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<S7UserRecord>> getKeys() {
        return Arrays.<UniqueKey<S7UserRecord>>asList(Keys.KEY_S7_USER_PRIMARY);
    }

    @Override
    public TS7User as(String alias) {
        return new TS7User(DSL.name(alias), this);
    }

    @Override
    public TS7User as(Name alias) {
        return new TS7User(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TS7User rename(String name) {
        return new TS7User(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TS7User rename(Name name) {
        return new TS7User(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
