/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.records;


import com.diamondfsd.jooq.learn.codegen.tables.TS4ColumenGt22;
import com.diamondfsd.jooq.learn.codegen.tables.interfaces.IS4ColumenGt22;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 表字段超22
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4ColumenGt22Record extends UpdatableRecordImpl<S4ColumenGt22Record> implements IS4ColumenGt22 {

    private static final long serialVersionUID = 1303428101;

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.id</code>. id
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.id</code>. id
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_1</code>. 列1
     */
    @Override
    public void setColumn_1(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_1</code>. 列1
     */
    @Override
    public Integer getColumn_1() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_2</code>. 列2
     */
    @Override
    public void setColumn_2(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_2</code>. 列2
     */
    @Override
    public Integer getColumn_2() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_3</code>. 列3
     */
    @Override
    public void setColumn_3(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_3</code>. 列3
     */
    @Override
    public Integer getColumn_3() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_4</code>. 列4
     */
    @Override
    public void setColumn_4(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_4</code>. 列4
     */
    @Override
    public Integer getColumn_4() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_5</code>. 列5
     */
    @Override
    public void setColumn_5(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_5</code>. 列5
     */
    @Override
    public Integer getColumn_5() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_6</code>. 列6
     */
    @Override
    public void setColumn_6(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_6</code>. 列6
     */
    @Override
    public Integer getColumn_6() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_7</code>. 列7
     */
    @Override
    public void setColumn_7(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_7</code>. 列7
     */
    @Override
    public Integer getColumn_7() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_8</code>. 列8
     */
    @Override
    public void setColumn_8(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_8</code>. 列8
     */
    @Override
    public Integer getColumn_8() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_9</code>. 列_9
     */
    @Override
    public void setColumn_9(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_9</code>. 列_9
     */
    @Override
    public Integer getColumn_9() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_10</code>. 列10
     */
    @Override
    public void setColumn_10(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_10</code>. 列10
     */
    @Override
    public Integer getColumn_10() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_11</code>. 列11
     */
    @Override
    public void setColumn_11(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_11</code>. 列11
     */
    @Override
    public Integer getColumn_11() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_12</code>. 列12
     */
    @Override
    public void setColumn_12(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_12</code>. 列12
     */
    @Override
    public Integer getColumn_12() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_13</code>. 列13
     */
    @Override
    public void setColumn_13(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_13</code>. 列13
     */
    @Override
    public Integer getColumn_13() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_14</code>. 列14
     */
    @Override
    public void setColumn_14(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_14</code>. 列14
     */
    @Override
    public Integer getColumn_14() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_15</code>. 列15
     */
    @Override
    public void setColumn_15(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_15</code>. 列15
     */
    @Override
    public Integer getColumn_15() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_16</code>. 列16
     */
    @Override
    public void setColumn_16(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_16</code>. 列16
     */
    @Override
    public String getColumn_16() {
        return (String) get(16);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_17</code>. 列17
     */
    @Override
    public void setColumn_17(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_17</code>. 列17
     */
    @Override
    public String getColumn_17() {
        return (String) get(17);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_18</code>. 列18
     */
    @Override
    public void setColumn_18(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_18</code>. 列18
     */
    @Override
    public String getColumn_18() {
        return (String) get(18);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_19</code>. 列19
     */
    @Override
    public void setColumn_19(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_19</code>. 列19
     */
    @Override
    public Timestamp getColumn_19() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_20</code>. 列20
     */
    @Override
    public void setColumn_20(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_20</code>. 列20
     */
    @Override
    public Boolean getColumn_20() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_21</code>. 列21
     */
    @Override
    public void setColumn_21(Byte value) {
        set(21, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_21</code>. 列21
     */
    @Override
    public Byte getColumn_21() {
        return (Byte) get(21);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_22</code>. 列22
     */
    @Override
    public void setColumn_22(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_22</code>. 列22
     */
    @Override
    public Integer getColumn_22() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.column_23</code>. 列23
     */
    @Override
    public void setColumn_23(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.column_23</code>. 列23
     */
    @Override
    public Integer getColumn_23() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.create_time</code>. 创建时间
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>learn-jooq.s4_columen_gt22.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>learn-jooq.s4_columen_gt22.update_time</code>. 更新时间
     */
    @Override
    public Timestamp getUpdateTime() {
        return (Timestamp) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS4ColumenGt22 from) {
        setId(from.getId());
        setColumn_1(from.getColumn_1());
        setColumn_2(from.getColumn_2());
        setColumn_3(from.getColumn_3());
        setColumn_4(from.getColumn_4());
        setColumn_5(from.getColumn_5());
        setColumn_6(from.getColumn_6());
        setColumn_7(from.getColumn_7());
        setColumn_8(from.getColumn_8());
        setColumn_9(from.getColumn_9());
        setColumn_10(from.getColumn_10());
        setColumn_11(from.getColumn_11());
        setColumn_12(from.getColumn_12());
        setColumn_13(from.getColumn_13());
        setColumn_14(from.getColumn_14());
        setColumn_15(from.getColumn_15());
        setColumn_16(from.getColumn_16());
        setColumn_17(from.getColumn_17());
        setColumn_18(from.getColumn_18());
        setColumn_19(from.getColumn_19());
        setColumn_20(from.getColumn_20());
        setColumn_21(from.getColumn_21());
        setColumn_22(from.getColumn_22());
        setColumn_23(from.getColumn_23());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS4ColumenGt22> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S4ColumenGt22Record
     */
    public S4ColumenGt22Record() {
        super(TS4ColumenGt22.S4_COLUMEN_GT22);
    }

    /**
     * Create a detached, initialised S4ColumenGt22Record
     */
    public S4ColumenGt22Record(Integer id, Integer column_1, Integer column_2, Integer column_3, Integer column_4, Integer column_5, Integer column_6, Integer column_7, Integer column_8, Integer column_9, Integer column_10, Integer column_11, Integer column_12, Integer column_13, Integer column_14, Integer column_15, String column_16, String column_17, String column_18, Timestamp column_19, Boolean column_20, Byte column_21, Integer column_22, Integer column_23, Timestamp createTime, Timestamp updateTime) {
        super(TS4ColumenGt22.S4_COLUMEN_GT22);

        set(0, id);
        set(1, column_1);
        set(2, column_2);
        set(3, column_3);
        set(4, column_4);
        set(5, column_5);
        set(6, column_6);
        set(7, column_7);
        set(8, column_8);
        set(9, column_9);
        set(10, column_10);
        set(11, column_11);
        set(12, column_12);
        set(13, column_13);
        set(14, column_14);
        set(15, column_15);
        set(16, column_16);
        set(17, column_17);
        set(18, column_18);
        set(19, column_19);
        set(20, column_20);
        set(21, column_21);
        set(22, column_22);
        set(23, column_23);
        set(24, createTime);
        set(25, updateTime);
    }
}
