/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.records;


import com.diamondfsd.jooq.learn.codegen.tables.TS9News;
import com.diamondfsd.jooq.learn.codegen.tables.interfaces.IS9News;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 新闻表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S9NewsRecord extends UpdatableRecordImpl<S9NewsRecord> implements Record5<Integer, String, String, Timestamp, Timestamp>, IS9News {

    private static final long serialVersionUID = -1349433613;

    /**
     * Setter for <code>learn-jooq.s9_news.id</code>. ID
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn-jooq.s9_news.id</code>. ID
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>learn-jooq.s9_news.title</code>. 标题
     */
    @Override
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn-jooq.s9_news.title</code>. 标题
     */
    @Override
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>learn-jooq.s9_news.content</code>. 内容
     */
    @Override
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn-jooq.s9_news.content</code>. 内容
     */
    @Override
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>learn-jooq.s9_news.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn-jooq.s9_news.create_time</code>. 创建时间
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>learn-jooq.s9_news.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn-jooq.s9_news.update_time</code>. 更新时间
     */
    @Override
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TS9News.S9_NEWS.ID;
    }

    @Override
    public Field<String> field2() {
        return TS9News.S9_NEWS.TITLE;
    }

    @Override
    public Field<String> field3() {
        return TS9News.S9_NEWS.CONTENT;
    }

    @Override
    public Field<Timestamp> field4() {
        return TS9News.S9_NEWS.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field5() {
        return TS9News.S9_NEWS.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    @Override
    public Timestamp component5() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    @Override
    public S9NewsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public S9NewsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public S9NewsRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public S9NewsRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public S9NewsRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public S9NewsRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS9News from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS9News> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S9NewsRecord
     */
    public S9NewsRecord() {
        super(TS9News.S9_NEWS);
    }

    /**
     * Create a detached, initialised S9NewsRecord
     */
    public S9NewsRecord(Integer id, String title, String content, Timestamp createTime, Timestamp updateTime) {
        super(TS9News.S9_NEWS);

        set(0, id);
        set(1, title);
        set(2, content);
        set(3, createTime);
        set(4, updateTime);
    }
}
