/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.daos;


import com.diamondfsd.jooq.learn.codegen.tables.TS1User;
import com.diamondfsd.jooq.learn.codegen.tables.pojos.S1UserPojo;
import com.diamondfsd.jooq.learn.codegen.tables.records.S1UserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1UserDao extends DAOImpl<S1UserRecord, S1UserPojo, Integer> {

    /**
     * Create a new S1UserDao without any configuration
     */
    public S1UserDao() {
        super(TS1User.S1_USER, S1UserPojo.class);
    }

    /**
     * Create a new S1UserDao with an attached configuration
     */
    public S1UserDao(Configuration configuration) {
        super(TS1User.S1_USER, S1UserPojo.class, configuration);
    }

    @Override
    public Integer getId(S1UserPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TS1User.S1_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<S1UserPojo> fetchById(Integer... values) {
        return fetch(TS1User.S1_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public S1UserPojo fetchOneById(Integer value) {
        return fetchOne(TS1User.S1_USER.ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<S1UserPojo> fetchByUsername(String... values) {
        return fetch(TS1User.S1_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<S1UserPojo> fetchByEmail(String... values) {
        return fetch(TS1User.S1_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>address BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(TS1User.S1_USER.ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<S1UserPojo> fetchByAddress(String... values) {
        return fetch(TS1User.S1_USER.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfCreateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS1User.S1_USER.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<S1UserPojo> fetchByCreateTime(Timestamp... values) {
        return fetch(TS1User.S1_USER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S1UserPojo> fetchRangeOfUpdateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS1User.S1_USER.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<S1UserPojo> fetchByUpdateTime(Timestamp... values) {
        return fetch(TS1User.S1_USER.UPDATE_TIME, values);
    }
}
