/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.daos;


import com.diamondfsd.jooq.learn.codegen.tables.TS4UnionKey;
import com.diamondfsd.jooq.learn.codegen.tables.pojos.S4UnionKeyPojo;
import com.diamondfsd.jooq.learn.codegen.tables.records.S4UnionKeyRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4UnionKeyDao extends DAOImpl<S4UnionKeyRecord, S4UnionKeyPojo, Record2<Integer, Integer>> {

    /**
     * Create a new S4UnionKeyDao without any configuration
     */
    public S4UnionKeyDao() {
        super(TS4UnionKey.S4_UNION_KEY, S4UnionKeyPojo.class);
    }

    /**
     * Create a new S4UnionKeyDao with an attached configuration
     */
    public S4UnionKeyDao(Configuration configuration) {
        super(TS4UnionKey.S4_UNION_KEY, S4UnionKeyPojo.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(S4UnionKeyPojo object) {
        return compositeKeyRecord(object.getUk_1(), object.getUk_2());
    }

    /**
     * Fetch records that have <code>uk_1 BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S4UnionKeyPojo> fetchRangeOfUk_1(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TS4UnionKey.S4_UNION_KEY.UK_1, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uk_1 IN (values)</code>
     */
    public List<S4UnionKeyPojo> fetchByUk_1(Integer... values) {
        return fetch(TS4UnionKey.S4_UNION_KEY.UK_1, values);
    }

    /**
     * Fetch records that have <code>uk_2 BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S4UnionKeyPojo> fetchRangeOfUk_2(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TS4UnionKey.S4_UNION_KEY.UK_2, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uk_2 IN (values)</code>
     */
    public List<S4UnionKeyPojo> fetchByUk_2(Integer... values) {
        return fetch(TS4UnionKey.S4_UNION_KEY.UK_2, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S4UnionKeyPojo> fetchRangeOfCreateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS4UnionKey.S4_UNION_KEY.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<S4UnionKeyPojo> fetchByCreateTime(Timestamp... values) {
        return fetch(TS4UnionKey.S4_UNION_KEY.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<S4UnionKeyPojo> fetchRangeOfUpdateTime(Timestamp lowerInclusive, Timestamp upperInclusive) {
        return fetchRange(TS4UnionKey.S4_UNION_KEY.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<S4UnionKeyPojo> fetchByUpdateTime(Timestamp... values) {
        return fetch(TS4UnionKey.S4_UNION_KEY.UPDATE_TIME, values);
    }
}
