/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.pojos;


import com.diamondfsd.jooq.learn.codegen.learn_jooq_2.tables.interfaces.IS7User;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * USER TABLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S7UserPojo implements IS7User {

    private static final long serialVersionUID = -719403906;

    private Integer   id;
    private String    username;
    private String    email;
    private String    address;
    private Timestamp createTime;
    private Timestamp updateTime;

    public S7UserPojo() {}

    public S7UserPojo(IS7User value) {
        this.id = value.getId();
        this.username = value.getUsername();
        this.email = value.getEmail();
        this.address = value.getAddress();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public S7UserPojo(
        Integer   id,
        String    username,
        String    email,
        String    address,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.address = address;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getAddress() {
        return this.address;
    }

    @Override
    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S7UserPojo (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(address);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IS7User from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setEmail(from.getEmail());
        setAddress(from.getAddress());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IS7User> E into(E into) {
        into.from(this);
        return into;
    }
}
