/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4NoPrimaryPojo implements Serializable {

    private static final long serialVersionUID = 977564452;

    private String    column1;
    private String    column2;
    private Timestamp createTime;
    private Timestamp updateTime;

    public S4NoPrimaryPojo() {}

    public S4NoPrimaryPojo(S4NoPrimaryPojo value) {
        this.column1 = value.column1;
        this.column2 = value.column2;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public S4NoPrimaryPojo(
        String    column1,
        String    column2,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.column1 = column1;
        this.column2 = column2;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public String getColumn1() {
        return this.column1;
    }

    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    public String getColumn2() {
        return this.column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S4NoPrimaryPojo (");

        sb.append(column1);
        sb.append(", ").append(column2);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
