/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4UnionKeyPojo implements Serializable {

    private static final long serialVersionUID = 1339293588;

    private Integer   uk_1;
    private Integer   uk_2;
    private Timestamp createTime;
    private Timestamp updateTime;

    public S4UnionKeyPojo() {}

    public S4UnionKeyPojo(S4UnionKeyPojo value) {
        this.uk_1 = value.uk_1;
        this.uk_2 = value.uk_2;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public S4UnionKeyPojo(
        Integer   uk_1,
        Integer   uk_2,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.uk_1 = uk_1;
        this.uk_2 = uk_2;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getUk_1() {
        return this.uk_1;
    }

    public void setUk_1(Integer uk_1) {
        this.uk_1 = uk_1;
    }

    public Integer getUk_2() {
        return this.uk_2;
    }

    public void setUk_2(Integer uk_2) {
        this.uk_2 = uk_2;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S4UnionKeyPojo (");

        sb.append(uk_1);
        sb.append(", ").append(uk_2);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
