/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.jooq.tables;


import com.diamondfsd.jooq.learn.jooq.Indexes;
import com.diamondfsd.jooq.learn.jooq.Keys;
import com.diamondfsd.jooq.learn.jooq.LearnJooq;
import com.diamondfsd.jooq.learn.jooq.tables.records.S9NewsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 新闻表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TS9News extends TableImpl<S9NewsRecord> {

    private static final long serialVersionUID = -1365056935;

    /**
     * The reference instance of <code>learn-jooq.s9_news</code>
     */
    public static final TS9News S9_NEWS = new TS9News();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<S9NewsRecord> getRecordType() {
        return S9NewsRecord.class;
    }

    /**
     * The column <code>learn-jooq.s9_news.id</code>. ID
     */
    public final TableField<S9NewsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "ID");

    /**
     * The column <code>learn-jooq.s9_news.title</code>. 标题
     */
    public final TableField<S9NewsRecord, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(60), this, "标题");

    /**
     * The column <code>learn-jooq.s9_news.content</code>. 内容
     */
    public final TableField<S9NewsRecord, String> CONTENT = createField(DSL.name("content"), org.jooq.impl.SQLDataType.VARCHAR(500), this, "内容");

    /**
     * The column <code>learn-jooq.s9_news.create_time</code>. 创建时间
     */
    public final TableField<S9NewsRecord, Timestamp> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>learn-jooq.s9_news.update_time</code>. 更新时间
     */
    public final TableField<S9NewsRecord, Timestamp> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>learn-jooq.s9_news</code> table reference
     */
    public TS9News() {
        this(DSL.name("s9_news"), null);
    }

    /**
     * Create an aliased <code>learn-jooq.s9_news</code> table reference
     */
    public TS9News(String alias) {
        this(DSL.name(alias), S9_NEWS);
    }

    /**
     * Create an aliased <code>learn-jooq.s9_news</code> table reference
     */
    public TS9News(Name alias) {
        this(alias, S9_NEWS);
    }

    private TS9News(Name alias, Table<S9NewsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TS9News(Name alias, Table<S9NewsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("新闻表"));
    }

    public <O extends Record> TS9News(Table<O> child, ForeignKey<O, S9NewsRecord> key) {
        super(child, key, S9_NEWS);
    }

    @Override
    public Schema getSchema() {
        return LearnJooq.LEARN_JOOQ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S9_NEWS_PRIMARY);
    }

    @Override
    public Identity<S9NewsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S9_NEWS;
    }

    @Override
    public UniqueKey<S9NewsRecord> getPrimaryKey() {
        return Keys.KEY_S9_NEWS_PRIMARY;
    }

    @Override
    public List<UniqueKey<S9NewsRecord>> getKeys() {
        return Arrays.<UniqueKey<S9NewsRecord>>asList(Keys.KEY_S9_NEWS_PRIMARY);
    }

    @Override
    public TS9News as(String alias) {
        return new TS9News(DSL.name(alias), this);
    }

    @Override
    public TS9News as(Name alias) {
        return new TS9News(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TS9News rename(String name) {
        return new TS9News(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TS9News rename(Name name) {
        return new TS9News(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
