/*
 * This file is generated by jOOQ.
 */
package com.diamondfsd.jooq.learn.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 新闻表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IS9News extends Serializable {

    /**
     * Setter for <code>learn-jooq.s9_news.id</code>. ID
     */
    public void setId(Integer value);

    /**
     * Getter for <code>learn-jooq.s9_news.id</code>. ID
     */
    public Integer getId();

    /**
     * Setter for <code>learn-jooq.s9_news.title</code>. 标题
     */
    public void setTitle(String value);

    /**
     * Getter for <code>learn-jooq.s9_news.title</code>. 标题
     */
    public String getTitle();

    /**
     * Setter for <code>learn-jooq.s9_news.content</code>. 内容
     */
    public void setContent(String value);

    /**
     * Getter for <code>learn-jooq.s9_news.content</code>. 内容
     */
    public String getContent();

    /**
     * Setter for <code>learn-jooq.s9_news.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s9_news.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime();

    /**
     * Setter for <code>learn-jooq.s9_news.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value);

    /**
     * Getter for <code>learn-jooq.s9_news.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IS9News
     */
    public void from(com.diamondfsd.jooq.learn.jooq.tables.interfaces.IS9News from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IS9News
     */
    public <E extends com.diamondfsd.jooq.learn.jooq.tables.interfaces.IS9News> E into(E into);
}
